// Questions
var q2 = [
	'What do you understand that others don&#39;t?',
	'Why will you succeed?',
	'How big an opportunity is there?',
	'What problems/hurdles are you anticipating?',
	'Who would use your product?',
	'How much does customer acquisition cost?',
	'How will you make money?',
	'How much money could you make per year?',
	'How many users do you have?',
	'What is your user growth rate?',
	'How many users are paying?',
	'How are you meeting customers?',
	'How are you understanding customer needs?',
	'How will you get users?',
	'Who would you hire or how would you add to your team?',
	
	'So what are you working on?',
	'Do you have a demo?',
	'Where is the rocket science here?',
	'How does your product work in more detail?',
	'How is your product different?',
	'What are you going to do next?',
	'What&#39;s new about what you make?',
	'What, exactly, makes you different from existing options?',
	'Who needs what you&#39;re making?',
	'How do you know customers need what you&#39;re making?',
	'Why isn&#39;t someone already doing this?',
	'What obstacles will you face and how will you overcome them?',
	'How will customers and/or users find out about you?',
	'What resistance will they have to trying you and how will you overcome it?',
	'What are the key things about your field that outsiders don&#39;t understand?',
	'What part of your project are you going to build first?',
	'Who is going to be your first paying customer?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'Why did you choose this idea?',
	'What have you learned so far from working on your product?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do new users come from?',
	'What is your growth like?',
	'What&#39;s the conversion rate?',
	'What makes new users try you?',
	'Why do the reluctant users hold back?',
	'What are the top things users want?',
	'What has surprised you about user behaviour?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your users?',
	'Why did you pick this idea to work on?',
	'What domain expertise do you have?',
	'Who are your competitors?',
	'Who might become competitors?',
	'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	'What competition do you fear most?',
	'What is your distribution strategy?',
	'How did your team meet?',
	'Why did your team get together?',
	'Who in your team does what?',
	'Who is &quot;the boss&quot;?',
	'What will you do if we don&#39;t fund you?',
	'Would you relocate to Silicon Valley?',
	'How do we know your team will stick together?',
	'What else have you created together?',
	'Are you open to changing your idea? ',
	'What systems have you hacked?',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'Will you reincorporate as a US company?',
	'Will your team stick at this?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'What is your burn rate?',
	'How long can you go before funding?',
	'What is the next step with the product evolution?',
	'Have you raised funding?',
	'Who would be your next hire?',
	
	'How do you know people want this?',
	'What do you know about this space/product others don&#39;t know?'
];

var q = [
    'What is the core problem Medly AI is solving?',
    'What specific evidence do you have that the traditional education system fails to unlock the full potential of all students?',
    'How did you identify this problem as a significant opportunity in the EdTech market?',
    'Who are the primary users of Medly AI?',
    'Why do you believe Medly AI will succeed where others have not?',
    'How have you validated the need for Medly AI in the market?',
    'Who needs Medly AI the most and why?',
    'What sets Medly AI apart from existing EdTech products?',
    'What unique features does Medly AI offer?',
    'Why hasn’t anyone successfully addressed this problem before?',
    'Why did you choose to work on Medly AI?',
    'What are the main technological innovations behind Medly AI?',
    'Can you give a brief overview of what Medly AI is working on?',
    'Do you have a demo available?',
    'How does Medly AI’s adaptive AI tutor function in detail?',
    'What data do you use to train your AI, and how is it proprietary?',
    'What will be the first part of the project you build?',
    'What are your immediate next steps in product development?',
    'What impressive milestones have you achieved with Medly AI?',
    'What has your growth trajectory been like so far?',
    'How many active users does Medly AI currently have?',
    'What is your current monthly user growth rate?',
    'How many users are currently paying for your service?',
    'What is your conversion rate from free to paid users?',
    'Where do your new users typically come from?',
    'What motivates new users to try Medly AI?',
    'What resistance might users have to Medly AI and how will you overcome it?',
    'What are the top features users want from Medly AI?',
    'What has surprised you the most about user behavior?',
    'How do you acquire new customers?',
    'How do you gather and respond to customer feedback?',
    'What strategies will you use to increase user acquisition?',
    'Can you quantify the market opportunity for Medly AI?',
    'Can you break down the £142B EdTech market and explain where Medly AI fits within this landscape?',
    'How do you plan to capture a significant share of the GenAI EdTech market, which is growing at 40.5% CAGR?',
    'What makes your curriculum-driven AI truly adaptive compared to other AI solutions?',
    'How does the integration of neuroscience and teaching theory enhance your product?',
    'What is your business model and how do you generate revenue?',
    'Can you explain the details of your B2C Freemium model and the expected conversion rates?',
    'How does the B2B dashboard for schools add value, and what is the pricing model?',
    'What are your projected revenues for the next three years?',
    'What are the key assumptions behind your projected growth rates and revenue forecast?',
    'What is your current Monthly Recurring Revenue (MRR), and how do you plan to scale it?',
    'What is your current customer acquisition cost?',
    'What are the key underlying assumptions in your financial projections?',
    'What is your breakeven point?',
    'What is your current burn rate, and how long can you sustain operations with your existing funds?',
    'Have you raised any funding so far?',
    'How will the £500K pre-seed round be allocated across different initiatives?',
    'What milestones do you aim to achieve with this funding, and in what timeframe?',
    'Who will be your first paying customer?',
    'What will you do if you don’t receive funding?',
    'If Medly AI succeeds, what are potential areas for expansion?',
    'What are the biggest challenges you foresee for Medly AI?',
    'What obstacles do you anticipate and how will you overcome them?',
    'How do you plan to defend against potential competition from large players like ChatGPT?',
    'Why wouldn’t a large player easily replicate your product?',
    'What’s your plan if a large competitor enters the market?',
    'How do you plan to maintain a competitive advantage in the rapidly evolving AI landscape?',
    'What deep understanding do you have about your users?',
    'What domain expertise does your team possess?',
    'How did your team come together?',
    'What are the roles and responsibilities within your team?',
    'Who makes the final decisions in your team?',
    'What makes you confident that your team will stay together?',
    'What other projects have you worked on together?',
    'Are you willing to pivot your idea if necessary?',
    'Can you share an example of a tough problem your team has solved?',
    'How resourceful is your team in overcoming challenges?',
    'What’s the funniest or most surprising thing that has happened during this project?',
    'What has been your biggest mistake so far?',
    'Who would be the next hire if you secure funding?',
    'What are the most critical positions you need to hire for next?',
    'How do you know there is demand for Medly AI?',
    'What unique knowledge does your team have about the EdTech space?',
    'How do you measure and track the educational outcomes and effectiveness of your AI tutor?',
    'What partnerships or collaborations are you seeking to enhance your product offering?',
    'What potential risks do you foresee in the execution of your business plan, and how do you mitigate them?',
    'How will you handle potential resistance from traditional educational institutions or educators?',
    'What impact has your partnership with UCL had on your product development and credibility?',
    'How do you ensure data privacy and security for your users, especially minors?',
    'What contingency plans do you have in place if you face regulatory challenges in different markets?',
	"What differentiates learning on ChatGPT with learning on Medly?",
	"What's the difference between ChatGPT and Medly?",
	"What is the architecture behind Medly?",
	"What differentiates Medly from Khanmigo?",
	"Is your data proprietary?",
	"What about GPT-4o vision?",
	"Isn't Medly just prompt engineering?",
	"What about GPTs (Khanmigo as a GPT)",
	"Does Medly hallucinate? How much does it hallucinate?",
	"How do you achieve memory?",
	"How does Medly adapt over time?",
	"How quickly/easily could a competitor recreate Medly?",
	"What is your competitive moat?",
	"What teaching theory is Medly based on?"	
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
